name: Build and Deploy React App

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: self-hosted  # Must match the EC2 runner label

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Copy Build to NGINX
        run: |
          sudo rm -rf /usr/share/nginx/html/*
          sudo cp -r build/* /usr/share/nginx/html/
